### PR TITLE
DDCYLS-3445 PPT: Navigate to new Application complete page 

### PR DESCRIPTION
**Pull request by tapiwa-tiyemba**

### CODE REVIEW

**Comment by tapiwa-tiyemba** [comment]
New page
application-complete
Welsh
welsh

**Comment by tapiwa-tiyemba** [comment]
Unit
Screenshot 2024-07-31 at 10 52 45
AT
Screenshot 2024-07-31 at 11 23 32

**Comment by tapiwa-tiyemba** [comment]
Uploading Screen Recording 2024-07-31 at 11.27.44 2-1-1.mov…

**Review by ashwinirudrappa — APPROVED** [review]
LGTM, A small minor comment on naming the page

**Review by ashwinirudrappa — APPROVED** [review]

**Pull request merged**
